power = {'BUSES': {'Area': 0.149364,
           'Bus/Area': 0.149364,
           'Bus/Gate Leakage': 0.000213707,
           'Bus/Peak Dynamic': 0.594358,
           'Bus/Runtime Dynamic': 0.0452941,
           'Bus/Subthreshold Leakage': 0.0153692,
           'Bus/Subthreshold Leakage with power gating': 0.00461077,
           'Gate Leakage': 0.000213707,
           'Peak Dynamic': 0.594358,
           'Runtime Dynamic': 0.0452941,
           'Subthreshold Leakage': 0.0153692,
           'Subthreshold Leakage with power gating': 0.00461077},
 'Core': [{'Area': 8.45611,
           'Execution Unit/Area': 2.14962,
           'Execution Unit/Complex ALUs/Area': 0.115363,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.000316407,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.243293,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.0390848,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0106595,
           'Execution Unit/Floating Point Units/Area': 1.11344,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.000763458,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.36494,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.0943076,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.0257203,
           'Execution Unit/Gate Leakage': 0.00229396,
           'Execution Unit/Instruction Scheduler/Area': 0.53269,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.0803106,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 4.09447e-05,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 0.848283,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.694615,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.00495177,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.00279839,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.000257818,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 0.250713,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.000189603,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 1.44458,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 1.18965,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 0.0233811,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.0133031,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 3.36823,
           'Execution Unit/Instruction Scheduler/ROB/Area': 0.201666,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 2.72708e-05,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 1.07537,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 0.777443,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 0.00444903,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 0.00184714,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 2.66171,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0327819,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0179486,
           'Execution Unit/Integer ALUs/Area': 0.230726,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.000632815,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.79233,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.818278,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.0781696,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.021319,
           'Execution Unit/Peak Dynamic': 4.84317,
           'Execution Unit/Register Files/Area': 0.133129,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.0496557,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 7.84697e-06,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0242462,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00109402,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.000371205,
           'Execution Unit/Register Files/Gate Leakage': 2.138e-05,
           'Execution Unit/Register Files/Integer RF/Area': 0.0834736,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 1.3533e-05,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.180204,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.1843,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00172228,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.000521558,
           'Execution Unit/Register Files/Peak Dynamic': 0.180204,
           'Execution Unit/Register Files/Runtime Dynamic': 0.208546,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.0028163,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.000892763,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0135028,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.000212232,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.438817,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 1.23709,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0262163,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0071499,
           'Execution Unit/Runtime Dynamic': 5.53385,
           'Execution Unit/Subthreshold Leakage': 0.277787,
           'Execution Unit/Subthreshold Leakage with power gating': 0.0848929,
           'Gate Leakage': 0.0089427,
           'Instruction Fetch Unit/Area': 1.27919,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.031053,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.00539744,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 2.16698e-05,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.00539744,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.00570481,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 4.43463e-06,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.00802062,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.00467732,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.000876881,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.000367388,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.00289767,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 2.7078e-06,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00398848,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.00232592,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00048391,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000197984,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0342172,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.00253692,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 1.552e-06,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.00717956,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.00239026,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000262308,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000105831,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0178625,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.00458876,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.00191983,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.153336,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 7.44666e-05,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.107627,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0567787,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0179173,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.00810978,
           'Instruction Fetch Unit/Gate Leakage': 0.00161561,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.00457032,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 2.16072e-06,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.399167,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.16738,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.000368864,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.00012853,
           'Instruction Fetch Unit/Instruction Cache/Area': 0.652161,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.000896735,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 4.49084,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.809132,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.0875977,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.0398556,
           'Instruction Fetch Unit/Instruction Decoder/Area': 0.427303,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.000530726,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 0.557586,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.350713,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.0861737,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.0235019,
           'Instruction Fetch Unit/Peak Dynamic': 5.74107,
           'Instruction Fetch Unit/Runtime Dynamic': 1.40187,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.201057,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.0747186,
           'L2/Area': 0.622965,
           'L2/Gate Leakage': 0.000483288,
           'L2/Peak Dynamic': 0.018865,
           'L2/Runtime Dynamic': 0.0133097,
           'L2/Subthreshold Leakage': 0.128373,
           'L2/Subthreshold Leakage with power gating': 0.0544083,
           'Load Store Unit/Area': 2.11353,
           'Load Store Unit/Data Cache/Area': 1.69426,
           'Load Store Unit/Data Cache/Gate Leakage': 0.00105245,
           'Load Store Unit/Data Cache/Peak Dynamic': 6.35586,
           'Load Store Unit/Data Cache/Runtime Dynamic': 2.83231,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.155946,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.0640915,
           'Load Store Unit/Gate Leakage': 0.0011876,
           'Load Store Unit/LoadQ/Area': 0.0207189,
           'Load Store Unit/LoadQ/Gate Leakage': 1.97785e-05,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.158113,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.158113,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00252286,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00143803,
           'Load Store Unit/Peak Dynamic': 6.85796,
           'Load Store Unit/Runtime Dynamic': 3.39459,
           'Load Store Unit/StoreQ/Area': 0.0247255,
           'Load Store Unit/StoreQ/Gate Leakage': 2.55214e-05,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.202084,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.404168,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0034342,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0019575,
           'Load Store Unit/Subthreshold Leakage': 0.166314,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.0686899,
           'Memory Management Unit/Area': 0.0478667,
           'Memory Management Unit/Dtlb/Area': 0.0217794,
           'Memory Management Unit/Dtlb/Gate Leakage': 2.64018e-05,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.122507,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.122802,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.00372634,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00212401,
           'Memory Management Unit/Gate Leakage': 0.000133538,
           'Memory Management Unit/Itlb/Area': 0.0153187,
           'Memory Management Unit/Itlb/Gate Leakage': 1.72825e-05,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.0751147,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0370547,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.00236017,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0013453,
           'Memory Management Unit/Peak Dynamic': 0.344388,
           'Memory Management Unit/Runtime Dynamic': 0.159857,
           'Memory Management Unit/Subthreshold Leakage': 0.010497,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.00467217,
           'Peak Dynamic': 20.7354,
           'Renaming Unit/Area': 0.0885597,
           'Renaming Unit/FP Front End RAT/Area': 0.0402703,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.000171325,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 2.26672,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0126281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.00719803,
           'Renaming Unit/Free List/Area': 0.00980768,
           'Renaming Unit/Free List/Gate Leakage': 1.08162e-06,
           'Renaming Unit/Free List/Peak Dynamic': 0.0245223,
           'Renaming Unit/Free List/Runtime Dynamic': 0.0308484,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.000150194,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 7.5768e-05,
           'Renaming Unit/Gate Leakage': 0.000274281,
           'Renaming Unit/Int Front End RAT/Area': 0.0277132,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 1.20209e-05,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 0.487067,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 0.288042,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.00156023,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.000889329,
           'Renaming Unit/Peak Dynamic': 2.92993,
           'Renaming Unit/Runtime Dynamic': 0.318891,
           'Renaming Unit/Subthreshold Leakage': 0.0187491,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.009366,
           'Runtime Dynamic': 10.8224,
           'Subthreshold Leakage': 1.16773,
           'Subthreshold Leakage with power gating': 0.39628},
          {'Area': 8.45611,
           'Execution Unit/Area': 2.14962,
           'Execution Unit/Complex ALUs/Area': 0.115363,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.000316407,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.243293,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.0390848,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0106595,
           'Execution Unit/Floating Point Units/Area': 1.11344,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.000763458,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.36494,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.0943076,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.0257203,
           'Execution Unit/Gate Leakage': 0.00229396,
           'Execution Unit/Instruction Scheduler/Area': 0.53269,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.0803106,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 4.09447e-05,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 0.848283,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.00495177,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.00279839,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.000257818,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 0.250713,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.000189603,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 1.44458,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 0.0233811,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.0133031,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 3.36823,
           'Execution Unit/Instruction Scheduler/ROB/Area': 0.201666,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 2.72708e-05,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 1.07537,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 0.00444903,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 0.00184714,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0327819,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0179486,
           'Execution Unit/Integer ALUs/Area': 0.230726,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.000632815,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.121647,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.0781696,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.021319,
           'Execution Unit/Peak Dynamic': 3.36823,
           'Execution Unit/Register Files/Area': 0.133129,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.0496557,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 7.84697e-06,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00109402,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.000371205,
           'Execution Unit/Register Files/Gate Leakage': 2.138e-05,
           'Execution Unit/Register Files/Integer RF/Area': 0.0834736,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 1.3533e-05,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00172228,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.000521558,
           'Execution Unit/Register Files/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.0028163,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.000892763,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0135028,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.000212232,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.0,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0262163,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0071499,
           'Execution Unit/Runtime Dynamic': 0.72988,
           'Execution Unit/Subthreshold Leakage': 0.277787,
           'Execution Unit/Subthreshold Leakage with power gating': 0.0848929,
           'Gate Leakage': 0.0089427,
           'Instruction Fetch Unit/Area': 1.27919,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.031053,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 2.16698e-05,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.00570481,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 4.43463e-06,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.00802062,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.000876881,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.000367388,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.00289767,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 2.7078e-06,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00398848,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00048391,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000197984,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0342172,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.00253692,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 1.552e-06,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.00717956,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000262308,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000105831,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.00458876,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.00191983,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.153336,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 7.44666e-05,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.107627,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0179173,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.00810978,
           'Instruction Fetch Unit/Gate Leakage': 0.00161561,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.00457032,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 2.16072e-06,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.399167,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.000368864,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.00012853,
           'Instruction Fetch Unit/Instruction Cache/Area': 0.652161,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.000896735,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.0875977,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.0398556,
           'Instruction Fetch Unit/Instruction Decoder/Area': 0.427303,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.000530726,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 0.557586,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.0861737,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.0235019,
           'Instruction Fetch Unit/Peak Dynamic': 1.0986,
           'Instruction Fetch Unit/Runtime Dynamic': 4.21188e-08,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.201057,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.0747186,
           'L2/Area': 0.622965,
           'L2/Gate Leakage': 0.000483288,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 3.9683e-07,
           'L2/Subthreshold Leakage': 0.128373,
           'L2/Subthreshold Leakage with power gating': 0.0544083,
           'Load Store Unit/Area': 2.11353,
           'Load Store Unit/Data Cache/Area': 1.69426,
           'Load Store Unit/Data Cache/Gate Leakage': 0.00105245,
           'Load Store Unit/Data Cache/Peak Dynamic': 0.882694,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.0,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.155946,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.0640915,
           'Load Store Unit/Gate Leakage': 0.0011876,
           'Load Store Unit/LoadQ/Area': 0.0207189,
           'Load Store Unit/LoadQ/Gate Leakage': 1.97785e-05,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00252286,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00143803,
           'Load Store Unit/Peak Dynamic': 0.882694,
           'Load Store Unit/Runtime Dynamic': 4.21188e-08,
           'Load Store Unit/StoreQ/Area': 0.0247255,
           'Load Store Unit/StoreQ/Gate Leakage': 2.55214e-05,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.0,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.0,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0034342,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0019575,
           'Load Store Unit/Subthreshold Leakage': 0.166314,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.0686899,
           'Memory Management Unit/Area': 0.0478667,
           'Memory Management Unit/Dtlb/Area': 0.0217794,
           'Memory Management Unit/Dtlb/Gate Leakage': 2.64018e-05,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.00372634,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00212401,
           'Memory Management Unit/Gate Leakage': 0.000133538,
           'Memory Management Unit/Itlb/Area': 0.0153187,
           'Memory Management Unit/Itlb/Gate Leakage': 1.72825e-05,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.0,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.00236017,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0013453,
           'Memory Management Unit/Peak Dynamic': 0.0758138,
           'Memory Management Unit/Runtime Dynamic': 4.21188e-08,
           'Memory Management Unit/Subthreshold Leakage': 0.010497,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.00467217,
           'Peak Dynamic': 8.35527,
           'Renaming Unit/Area': 0.0885597,
           'Renaming Unit/FP Front End RAT/Area': 0.0402703,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.000171325,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 2.26672,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0126281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.00719803,
           'Renaming Unit/Free List/Area': 0.00980768,
           'Renaming Unit/Free List/Gate Leakage': 1.08162e-06,
           'Renaming Unit/Free List/Peak Dynamic': 0.0245223,
           'Renaming Unit/Free List/Runtime Dynamic': 0.0,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.000150194,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 7.5768e-05,
           'Renaming Unit/Gate Leakage': 0.000274281,
           'Renaming Unit/Int Front End RAT/Area': 0.0277132,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 1.20209e-05,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 0.487067,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.00156023,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.000889329,
           'Renaming Unit/Peak Dynamic': 2.92993,
           'Renaming Unit/Runtime Dynamic': 4.21188e-08,
           'Renaming Unit/Subthreshold Leakage': 0.0187491,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.009366,
           'Runtime Dynamic': 0.72988,
           'Subthreshold Leakage': 1.16773,
           'Subthreshold Leakage with power gating': 0.39628},
          {'Area': 8.45611,
           'Execution Unit/Area': 2.14962,
           'Execution Unit/Complex ALUs/Area': 0.115363,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.000316407,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.243293,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.0390848,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0106595,
           'Execution Unit/Floating Point Units/Area': 1.11344,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.000763458,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.36494,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.0943076,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.0257203,
           'Execution Unit/Gate Leakage': 0.00229396,
           'Execution Unit/Instruction Scheduler/Area': 0.53269,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.0803106,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 4.09447e-05,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 0.848283,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.00495177,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.00279839,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.000257818,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 0.250713,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.000189603,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 1.44458,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 0.0233811,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.0133031,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 3.36823,
           'Execution Unit/Instruction Scheduler/ROB/Area': 0.201666,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 2.72708e-05,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 1.07537,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 0.00444903,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 0.00184714,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0327819,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0179486,
           'Execution Unit/Integer ALUs/Area': 0.230726,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.000632815,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.121647,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.0781696,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.021319,
           'Execution Unit/Peak Dynamic': 3.36823,
           'Execution Unit/Register Files/Area': 0.133129,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.0496557,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 7.84697e-06,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00109402,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.000371205,
           'Execution Unit/Register Files/Gate Leakage': 2.138e-05,
           'Execution Unit/Register Files/Integer RF/Area': 0.0834736,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 1.3533e-05,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00172228,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.000521558,
           'Execution Unit/Register Files/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.0028163,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.000892763,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0135028,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.000212232,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.0,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0262163,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0071499,
           'Execution Unit/Runtime Dynamic': 0.72988,
           'Execution Unit/Subthreshold Leakage': 0.277787,
           'Execution Unit/Subthreshold Leakage with power gating': 0.0848929,
           'Gate Leakage': 0.0089427,
           'Instruction Fetch Unit/Area': 1.27919,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.031053,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 2.16698e-05,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.00570481,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 4.43463e-06,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.00802062,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.000876881,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.000367388,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.00289767,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 2.7078e-06,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00398848,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00048391,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000197984,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0342172,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.00253692,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 1.552e-06,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.00717956,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000262308,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000105831,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.00458876,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.00191983,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.153336,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 7.44666e-05,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.107627,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0179173,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.00810978,
           'Instruction Fetch Unit/Gate Leakage': 0.00161561,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.00457032,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 2.16072e-06,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.399167,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.000368864,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.00012853,
           'Instruction Fetch Unit/Instruction Cache/Area': 0.652161,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.000896735,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.0875977,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.0398556,
           'Instruction Fetch Unit/Instruction Decoder/Area': 0.427303,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.000530726,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 0.557586,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.0861737,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.0235019,
           'Instruction Fetch Unit/Peak Dynamic': 1.0986,
           'Instruction Fetch Unit/Runtime Dynamic': 4.21188e-08,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.201057,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.0747186,
           'L2/Area': 0.622965,
           'L2/Gate Leakage': 0.000483288,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 3.9683e-07,
           'L2/Subthreshold Leakage': 0.128373,
           'L2/Subthreshold Leakage with power gating': 0.0544083,
           'Load Store Unit/Area': 2.11353,
           'Load Store Unit/Data Cache/Area': 1.69426,
           'Load Store Unit/Data Cache/Gate Leakage': 0.00105245,
           'Load Store Unit/Data Cache/Peak Dynamic': 0.882694,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.0,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.155946,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.0640915,
           'Load Store Unit/Gate Leakage': 0.0011876,
           'Load Store Unit/LoadQ/Area': 0.0207189,
           'Load Store Unit/LoadQ/Gate Leakage': 1.97785e-05,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00252286,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00143803,
           'Load Store Unit/Peak Dynamic': 0.882694,
           'Load Store Unit/Runtime Dynamic': 4.21188e-08,
           'Load Store Unit/StoreQ/Area': 0.0247255,
           'Load Store Unit/StoreQ/Gate Leakage': 2.55214e-05,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.0,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.0,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0034342,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0019575,
           'Load Store Unit/Subthreshold Leakage': 0.166314,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.0686899,
           'Memory Management Unit/Area': 0.0478667,
           'Memory Management Unit/Dtlb/Area': 0.0217794,
           'Memory Management Unit/Dtlb/Gate Leakage': 2.64018e-05,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.00372634,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00212401,
           'Memory Management Unit/Gate Leakage': 0.000133538,
           'Memory Management Unit/Itlb/Area': 0.0153187,
           'Memory Management Unit/Itlb/Gate Leakage': 1.72825e-05,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.0,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.00236017,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0013453,
           'Memory Management Unit/Peak Dynamic': 0.0758138,
           'Memory Management Unit/Runtime Dynamic': 4.21188e-08,
           'Memory Management Unit/Subthreshold Leakage': 0.010497,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.00467217,
           'Peak Dynamic': 8.35527,
           'Renaming Unit/Area': 0.0885597,
           'Renaming Unit/FP Front End RAT/Area': 0.0402703,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.000171325,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 2.26672,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0126281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.00719803,
           'Renaming Unit/Free List/Area': 0.00980768,
           'Renaming Unit/Free List/Gate Leakage': 1.08162e-06,
           'Renaming Unit/Free List/Peak Dynamic': 0.0245223,
           'Renaming Unit/Free List/Runtime Dynamic': 0.0,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.000150194,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 7.5768e-05,
           'Renaming Unit/Gate Leakage': 0.000274281,
           'Renaming Unit/Int Front End RAT/Area': 0.0277132,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 1.20209e-05,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 0.487067,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.00156023,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.000889329,
           'Renaming Unit/Peak Dynamic': 2.92993,
           'Renaming Unit/Runtime Dynamic': 4.21188e-08,
           'Renaming Unit/Subthreshold Leakage': 0.0187491,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.009366,
           'Runtime Dynamic': 0.72988,
           'Subthreshold Leakage': 1.16773,
           'Subthreshold Leakage with power gating': 0.39628},
          {'Area': 8.45611,
           'Execution Unit/Area': 2.14962,
           'Execution Unit/Complex ALUs/Area': 0.115363,
           'Execution Unit/Complex ALUs/Gate Leakage': 0.000316407,
           'Execution Unit/Complex ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Complex ALUs/Runtime Dynamic': 0.243293,
           'Execution Unit/Complex ALUs/Subthreshold Leakage': 0.0390848,
           'Execution Unit/Complex ALUs/Subthreshold Leakage with power gating': 0.0106595,
           'Execution Unit/Floating Point Units/Area': 1.11344,
           'Execution Unit/Floating Point Units/Gate Leakage': 0.000763458,
           'Execution Unit/Floating Point Units/Peak Dynamic': 0.0,
           'Execution Unit/Floating Point Units/Runtime Dynamic': 0.36494,
           'Execution Unit/Floating Point Units/Subthreshold Leakage': 0.0943076,
           'Execution Unit/Floating Point Units/Subthreshold Leakage with power gating': 0.0257203,
           'Execution Unit/Gate Leakage': 0.00229396,
           'Execution Unit/Instruction Scheduler/Area': 0.53269,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Area': 0.0803106,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Gate Leakage': 4.09447e-05,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Peak Dynamic': 0.848283,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage': 0.00495177,
           'Execution Unit/Instruction Scheduler/FP Instruction Window/Subthreshold Leakage with power gating': 0.00279839,
           'Execution Unit/Instruction Scheduler/Gate Leakage': 0.000257818,
           'Execution Unit/Instruction Scheduler/Instruction Window/Area': 0.250713,
           'Execution Unit/Instruction Scheduler/Instruction Window/Gate Leakage': 0.000189603,
           'Execution Unit/Instruction Scheduler/Instruction Window/Peak Dynamic': 1.44458,
           'Execution Unit/Instruction Scheduler/Instruction Window/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage': 0.0233811,
           'Execution Unit/Instruction Scheduler/Instruction Window/Subthreshold Leakage with power gating': 0.0133031,
           'Execution Unit/Instruction Scheduler/Peak Dynamic': 3.36823,
           'Execution Unit/Instruction Scheduler/ROB/Area': 0.201666,
           'Execution Unit/Instruction Scheduler/ROB/Gate Leakage': 2.72708e-05,
           'Execution Unit/Instruction Scheduler/ROB/Peak Dynamic': 1.07537,
           'Execution Unit/Instruction Scheduler/ROB/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage': 0.00444903,
           'Execution Unit/Instruction Scheduler/ROB/Subthreshold Leakage with power gating': 0.00184714,
           'Execution Unit/Instruction Scheduler/Runtime Dynamic': 0.0,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage': 0.0327819,
           'Execution Unit/Instruction Scheduler/Subthreshold Leakage with power gating': 0.0179486,
           'Execution Unit/Integer ALUs/Area': 0.230726,
           'Execution Unit/Integer ALUs/Gate Leakage': 0.000632815,
           'Execution Unit/Integer ALUs/Peak Dynamic': 0.0,
           'Execution Unit/Integer ALUs/Runtime Dynamic': 0.121647,
           'Execution Unit/Integer ALUs/Subthreshold Leakage': 0.0781696,
           'Execution Unit/Integer ALUs/Subthreshold Leakage with power gating': 0.021319,
           'Execution Unit/Peak Dynamic': 3.36823,
           'Execution Unit/Register Files/Area': 0.133129,
           'Execution Unit/Register Files/Floating Point RF/Area': 0.0496557,
           'Execution Unit/Register Files/Floating Point RF/Gate Leakage': 7.84697e-06,
           'Execution Unit/Register Files/Floating Point RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage': 0.00109402,
           'Execution Unit/Register Files/Floating Point RF/Subthreshold Leakage with power gating': 0.000371205,
           'Execution Unit/Register Files/Gate Leakage': 2.138e-05,
           'Execution Unit/Register Files/Integer RF/Area': 0.0834736,
           'Execution Unit/Register Files/Integer RF/Gate Leakage': 1.3533e-05,
           'Execution Unit/Register Files/Integer RF/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Integer RF/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage': 0.00172228,
           'Execution Unit/Register Files/Integer RF/Subthreshold Leakage with power gating': 0.000521558,
           'Execution Unit/Register Files/Peak Dynamic': 0.0,
           'Execution Unit/Register Files/Runtime Dynamic': 0.0,
           'Execution Unit/Register Files/Subthreshold Leakage': 0.0028163,
           'Execution Unit/Register Files/Subthreshold Leakage with power gating': 0.000892763,
           'Execution Unit/Results Broadcast Bus/Area Overhead': 0.0135028,
           'Execution Unit/Results Broadcast Bus/Gate Leakage': 0.000212232,
           'Execution Unit/Results Broadcast Bus/Peak Dynamic': 0.0,
           'Execution Unit/Results Broadcast Bus/Runtime Dynamic': 0.0,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage': 0.0262163,
           'Execution Unit/Results Broadcast Bus/Subthreshold Leakage with power gating': 0.0071499,
           'Execution Unit/Runtime Dynamic': 0.72988,
           'Execution Unit/Subthreshold Leakage': 0.277787,
           'Execution Unit/Subthreshold Leakage with power gating': 0.0848929,
           'Gate Leakage': 0.0089427,
           'Instruction Fetch Unit/Area': 1.27919,
           'Instruction Fetch Unit/Branch Predictor/Area': 0.031053,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Chooser/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/Gate Leakage': 2.16698e-05,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Area': 0.00995681,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Gate Leakage': 7.8416e-06,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Peak Dynamic': 0.00950852,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage': 0.00172478,
           'Instruction Fetch Unit/Branch Predictor/Global Predictor/Subthreshold Leakage with power gating': 0.000723306,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Area': 0.00570481,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Gate Leakage': 4.43463e-06,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Peak Dynamic': 0.00802062,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage': 0.000876881,
           'Instruction Fetch Unit/Branch Predictor/L1_Local Predictor/Subthreshold Leakage with power gating': 0.000367388,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Area': 0.00289767,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Gate Leakage': 2.7078e-06,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Peak Dynamic': 0.00398848,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage': 0.00048391,
           'Instruction Fetch Unit/Branch Predictor/L2_Local Predictor/Subthreshold Leakage with power gating': 0.000197984,
           'Instruction Fetch Unit/Branch Predictor/Peak Dynamic': 0.0342172,
           'Instruction Fetch Unit/Branch Predictor/RAS/Area': 0.00253692,
           'Instruction Fetch Unit/Branch Predictor/RAS/Gate Leakage': 1.552e-06,
           'Instruction Fetch Unit/Branch Predictor/RAS/Peak Dynamic': 0.00717956,
           'Instruction Fetch Unit/Branch Predictor/RAS/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage': 0.000262308,
           'Instruction Fetch Unit/Branch Predictor/RAS/Subthreshold Leakage with power gating': 0.000105831,
           'Instruction Fetch Unit/Branch Predictor/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage': 0.00458876,
           'Instruction Fetch Unit/Branch Predictor/Subthreshold Leakage with power gating': 0.00191983,
           'Instruction Fetch Unit/Branch Target Buffer/Area': 0.153336,
           'Instruction Fetch Unit/Branch Target Buffer/Gate Leakage': 7.44666e-05,
           'Instruction Fetch Unit/Branch Target Buffer/Peak Dynamic': 0.107627,
           'Instruction Fetch Unit/Branch Target Buffer/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage': 0.0179173,
           'Instruction Fetch Unit/Branch Target Buffer/Subthreshold Leakage with power gating': 0.00810978,
           'Instruction Fetch Unit/Gate Leakage': 0.00161561,
           'Instruction Fetch Unit/Instruction Buffer/Area': 0.00457032,
           'Instruction Fetch Unit/Instruction Buffer/Gate Leakage': 2.16072e-06,
           'Instruction Fetch Unit/Instruction Buffer/Peak Dynamic': 0.399167,
           'Instruction Fetch Unit/Instruction Buffer/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage': 0.000368864,
           'Instruction Fetch Unit/Instruction Buffer/Subthreshold Leakage with power gating': 0.00012853,
           'Instruction Fetch Unit/Instruction Cache/Area': 0.652161,
           'Instruction Fetch Unit/Instruction Cache/Gate Leakage': 0.000896735,
           'Instruction Fetch Unit/Instruction Cache/Peak Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Cache/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage': 0.0875977,
           'Instruction Fetch Unit/Instruction Cache/Subthreshold Leakage with power gating': 0.0398556,
           'Instruction Fetch Unit/Instruction Decoder/Area': 0.427303,
           'Instruction Fetch Unit/Instruction Decoder/Gate Leakage': 0.000530726,
           'Instruction Fetch Unit/Instruction Decoder/Peak Dynamic': 0.557586,
           'Instruction Fetch Unit/Instruction Decoder/Runtime Dynamic': 0.0,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage': 0.0861737,
           'Instruction Fetch Unit/Instruction Decoder/Subthreshold Leakage with power gating': 0.0235019,
           'Instruction Fetch Unit/Peak Dynamic': 1.0986,
           'Instruction Fetch Unit/Runtime Dynamic': 4.21188e-08,
           'Instruction Fetch Unit/Subthreshold Leakage': 0.201057,
           'Instruction Fetch Unit/Subthreshold Leakage with power gating': 0.0747186,
           'L2/Area': 0.622965,
           'L2/Gate Leakage': 0.000483288,
           'L2/Peak Dynamic': 0.0,
           'L2/Runtime Dynamic': 3.9683e-07,
           'L2/Subthreshold Leakage': 0.128373,
           'L2/Subthreshold Leakage with power gating': 0.0544083,
           'Load Store Unit/Area': 2.11353,
           'Load Store Unit/Data Cache/Area': 1.69426,
           'Load Store Unit/Data Cache/Gate Leakage': 0.00105245,
           'Load Store Unit/Data Cache/Peak Dynamic': 0.882694,
           'Load Store Unit/Data Cache/Runtime Dynamic': 0.0,
           'Load Store Unit/Data Cache/Subthreshold Leakage': 0.155946,
           'Load Store Unit/Data Cache/Subthreshold Leakage with power gating': 0.0640915,
           'Load Store Unit/Gate Leakage': 0.0011876,
           'Load Store Unit/LoadQ/Area': 0.0207189,
           'Load Store Unit/LoadQ/Gate Leakage': 1.97785e-05,
           'Load Store Unit/LoadQ/Peak Dynamic': 0.0,
           'Load Store Unit/LoadQ/Runtime Dynamic': 0.0,
           'Load Store Unit/LoadQ/Subthreshold Leakage': 0.00252286,
           'Load Store Unit/LoadQ/Subthreshold Leakage with power gating': 0.00143803,
           'Load Store Unit/Peak Dynamic': 0.882694,
           'Load Store Unit/Runtime Dynamic': 4.21188e-08,
           'Load Store Unit/StoreQ/Area': 0.0247255,
           'Load Store Unit/StoreQ/Gate Leakage': 2.55214e-05,
           'Load Store Unit/StoreQ/Peak Dynamic': 0.0,
           'Load Store Unit/StoreQ/Runtime Dynamic': 0.0,
           'Load Store Unit/StoreQ/Subthreshold Leakage': 0.0034342,
           'Load Store Unit/StoreQ/Subthreshold Leakage with power gating': 0.0019575,
           'Load Store Unit/Subthreshold Leakage': 0.166314,
           'Load Store Unit/Subthreshold Leakage with power gating': 0.0686899,
           'Memory Management Unit/Area': 0.0478667,
           'Memory Management Unit/Dtlb/Area': 0.0217794,
           'Memory Management Unit/Dtlb/Gate Leakage': 2.64018e-05,
           'Memory Management Unit/Dtlb/Peak Dynamic': 0.0,
           'Memory Management Unit/Dtlb/Runtime Dynamic': 0.0,
           'Memory Management Unit/Dtlb/Subthreshold Leakage': 0.00372634,
           'Memory Management Unit/Dtlb/Subthreshold Leakage with power gating': 0.00212401,
           'Memory Management Unit/Gate Leakage': 0.000133538,
           'Memory Management Unit/Itlb/Area': 0.0153187,
           'Memory Management Unit/Itlb/Gate Leakage': 1.72825e-05,
           'Memory Management Unit/Itlb/Peak Dynamic': 0.0,
           'Memory Management Unit/Itlb/Runtime Dynamic': 0.0,
           'Memory Management Unit/Itlb/Subthreshold Leakage': 0.00236017,
           'Memory Management Unit/Itlb/Subthreshold Leakage with power gating': 0.0013453,
           'Memory Management Unit/Peak Dynamic': 0.0758138,
           'Memory Management Unit/Runtime Dynamic': 4.21188e-08,
           'Memory Management Unit/Subthreshold Leakage': 0.010497,
           'Memory Management Unit/Subthreshold Leakage with power gating': 0.00467217,
           'Peak Dynamic': 8.35527,
           'Renaming Unit/Area': 0.0885597,
           'Renaming Unit/FP Front End RAT/Area': 0.0402703,
           'Renaming Unit/FP Front End RAT/Gate Leakage': 0.000171325,
           'Renaming Unit/FP Front End RAT/Peak Dynamic': 2.26672,
           'Renaming Unit/FP Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage': 0.0126281,
           'Renaming Unit/FP Front End RAT/Subthreshold Leakage with power gating': 0.00719803,
           'Renaming Unit/Free List/Area': 0.00980768,
           'Renaming Unit/Free List/Gate Leakage': 1.08162e-06,
           'Renaming Unit/Free List/Peak Dynamic': 0.0245223,
           'Renaming Unit/Free List/Runtime Dynamic': 0.0,
           'Renaming Unit/Free List/Subthreshold Leakage': 0.000150194,
           'Renaming Unit/Free List/Subthreshold Leakage with power gating': 7.5768e-05,
           'Renaming Unit/Gate Leakage': 0.000274281,
           'Renaming Unit/Int Front End RAT/Area': 0.0277132,
           'Renaming Unit/Int Front End RAT/Gate Leakage': 1.20209e-05,
           'Renaming Unit/Int Front End RAT/Peak Dynamic': 0.487067,
           'Renaming Unit/Int Front End RAT/Runtime Dynamic': 0.0,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage': 0.00156023,
           'Renaming Unit/Int Front End RAT/Subthreshold Leakage with power gating': 0.000889329,
           'Renaming Unit/Peak Dynamic': 2.92993,
           'Renaming Unit/Runtime Dynamic': 4.21188e-08,
           'Renaming Unit/Subthreshold Leakage': 0.0187491,
           'Renaming Unit/Subthreshold Leakage with power gating': 0.009366,
           'Runtime Dynamic': 0.72988,
           'Subthreshold Leakage': 1.16773,
           'Subthreshold Leakage with power gating': 0.39628}],
 'DRAM': {'Area': 0,
          'Gate Leakage': 0,
          'Peak Dynamic': 2.9484285112781956,
          'Runtime Dynamic': 2.9484285112781956,
          'Subthreshold Leakage': 17.008,
          'Subthreshold Leakage with power gating': 17.008},
 'Processor': {'Area': 33.9738,
               'Gate Leakage': 0.0359845,
               'Peak Dynamic': 46.3956,
               'Peak Power': 51.1178,
               'Runtime Dynamic': 13.0573,
               'Subthreshold Leakage': 4.68627,
               'Subthreshold Leakage with power gating': 1.58948,
               'Total Cores/Area': 33.8245,
               'Total Cores/Gate Leakage': 0.0357708,
               'Total Cores/Peak Dynamic': 45.8012,
               'Total Cores/Runtime Dynamic': 13.012,
               'Total Cores/Subthreshold Leakage': 4.6709,
               'Total Cores/Subthreshold Leakage with power gating': 1.58512,
               'Total Leakage': 4.72226,
               'Total NoCs/Area': 0.149364,
               'Total NoCs/Gate Leakage': 0.000213707,
               'Total NoCs/Peak Dynamic': 0.594358,
               'Total NoCs/Runtime Dynamic': 0.0452941,
               'Total NoCs/Subthreshold Leakage': 0.0153692,
               'Total NoCs/Subthreshold Leakage with power gating': 0.00461077}}